### ISSUE TITLE
[REQUEST] Wallpaper set

### ISSUE THREAD

**Issue by ghost** [dylanaraps/bum#1]
Something that would be cool, is if the program could set the album art as your wallpaper. I scripted [something that does that](https://gist.github.com/tohd/a79d317c64e6e2f6cdb4c1e3b9ca9cca) but its sorta glitchy atm.

**Comment by dylanaraps** [comment]
(*Sorry, I didn't get a notification for this, I didn't know it existed till now.*)

I think this is out of scope for `bum`. You could easily script this using `mpc idle player` in a `while loop`. Example:

```sh
#!/bin/sh

bum &

while :; do
    # "mpc idle" is a way to loop without sleeping on intervals, 
    # it waits for a song change and then loops.
    mpc idle player >/dev/null
    feh --bg-fill "${HOME}/.cache/bum/current.jpg"

    # OR using wal.
    # wal -i "${HOME}/.cache/bum/current.jpg" -c
done
```
