### ISSUE TITLE
Infinite loop on network failure

### ISSUE THREAD

**Issue by Gadgetoid** [dylanaraps/bum#12]
In brainz.py, if it fails to connect to musicbrainz.org it will immediately retry by recursively calling the `get_cover` function. This would effectively lock up the process, repeatedly hitting musicbrainz.org in case of network or service issues.

I've put together a naive fix for this, which you can find here- https://github.com/pimoroni/bum/commit/0dbe80777527f63bad9418e137fb7e27344f8122

Would you be interested in a PR?

**Comment by dylanaraps** [comment]
Sure :+1:

**Comment by Gadgetoid** [comment]
Great! I've created a patch branch and raised a PR.

I'm currently working on a whole bunch of changes that you may or may not be interested in, in summary I want to allow `bum` to output using a variety of GUI tools or physical hardware displays by making the "display" type a pluggable class with a standard interface, and also support a variety of music players using pluggable "client" classes.

On top of this I want to draw an overlay over the album art which communicates status, title and remaining play time. This seems at odds with the very clean album-art-only approach that bum takes and is named for, though, so I'd fully understand if it didn't fit your vision.
