### ISSUE TITLE
Add option for remote MPD server

### ISSUE THREAD

**Issue by ghost** [dylanaraps/bum#6]
Hey Dylan! It would be great to have the option to connect to a non-localhost server. I found localhost hardcoded into song.py, changing it to one of my MPD server IPs seems to work.

**Comment by dylanaraps** [comment]
Done. 

I don't use `mpd`/`mopidy` anymore. Are you able to test master before I push a release?

**Comment by ghost** [comment]
Yes sir

**Comment by ghost** [comment]
Works perfectly. Thanks
